apiVersion: v2
name: victoria-logs-single
description: victoria-logs-single with Copa-patched container images
type: application
version: 0.11.26-0
dependencies:
  - name: victoria-logs-single
    version: 0.11.26
    repository: https://victoriametrics.github.io/helm-charts
