victoria-logs-single:
    server:
        image:
            registry: ghcr.io/descope
            repository: victoriametrics/victoria-logs
            tag: v1.43.1-patched
    vector:
        haproxy:
            image:
                registry: ghcr.io/descope
                repository: haproxytech/haproxy-alpine
                tag: 2.6.12-patched
        image:
            registry: ghcr.io/descope
            repository: timberio/vector
            tag: 0.50.0-debian-patched
