victoria-logs-single:
  server:
    image:
      registry: quay.io/verity
      repository: victoriametrics/victoria-logs
      tag: v1.43.1-patched
  vector:
    haproxy:
      image:
        registry: quay.io/verity
        repository: haproxytech/haproxy-alpine
        tag: 2.6.12-patched
    image:
      registry: quay.io/verity
      repository: timberio/vector
      tag: 0.50.0-debian-patched
