# NOTE: timberio/vector was overridden from "0.50.0-distroless-libc" to "0.50.0-debian" for Copa compatibility
victoria-logs-single:
    vector:
        image:
            registry: ghcr.io/descope
            repository: timberio/vector
            tag: 0.50.0-debian-patched
