# Standalone container images to patch with Copa.
# Renovate automatically picks up this file (helm-values manager).

# Image tag overrides for Copa-incompatible variants.
# Copa cannot patch distroless Alpine or scratch images.
# Use overrides to swap unpatchable variants with Copa-compatible ones.
overrides:
  timberio/vector:
    from: "distroless-libc"
    to: "debian"

redis-exporter:
  image:
    registry: quay.io
    repository: opstree/redis-exporter
    tag: "v1.80.2"

redis:
  image:
    registry: quay.io
    repository: opstree/redis
    tag: "v8.4.0"

redis-sentinel:
  image:
    registry: quay.io
    repository: opstree/redis-sentinel
    tag: "v8.4.0"

grafana:
  image:
    registry: docker.io
    repository: grafana/grafana
    tag: "12.3.3"

prometheus-config-reloader:
  image:
    registry: quay.io
    repository: prometheus-operator/prometheus-config-reloader
    tag: "v0.89.0"

prometheus:
  image:
    registry: quay.io
    repository: prometheus/prometheus
    tag: "v3.9.1"

k8s-sidecar:
  image:
    registry: ghcr.io
    repository: kiwigrid/k8s-sidecar
    tag: "2.5.0"

rabbitmqoperator:
  image:
    registry: docker.io
    repository: rabbitmqoperator/cluster-operator
    tag: "2.19.1"

rabbitmq:
  image:
    registry: docker.io
    repository: library/rabbitmq
    tag: "4.2.3"
