apiVersion: v2
name: postgres-operator
description: postgres-operator with Copa-patched container images
type: application
version: 1.15.1-0
dependencies:
  - name: postgres-operator
    version: 1.15.1
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
