apiVersion: v2
name: prometheus
description: prometheus with Copa-patched container images
type: application
version: 25.8.0-1
dependencies:
    - name: prometheus
      version: 25.8.0
      repository: oci://ghcr.io/prometheus-community/charts
