apiVersion: v2
name: prometheus
description: prometheus with Copa-patched container images
type: application
version: 28.9.1-3
dependencies:
    - name: prometheus
      version: 28.9.1
      repository: oci://ghcr.io/prometheus-community/charts
