prometheus:
    alertmanager:
        image:
            registry: quay.io
            repository: prometheus/alertmanager
            tag: v0.31.0
    configmapReload:
        prometheus:
            image:
                registry: quay.io
                repository: prometheus-operator/prometheus-config-reloader
                tag: v0.89.0
    kube-state-metrics:
        image:
            registry: registry.k8s.io
            repository: kube-state-metrics/kube-state-metrics
            tag: v2.18.0
    prometheus-node-exporter:
        image:
            registry: quay.io
            repository: prometheus/node-exporter
            tag: v1.10.2
        kubeRBACProxy:
            image:
                registry: quay.io
                repository: brancz/kube-rbac-proxy
                tag: v0.20.2
    prometheus-pushgateway:
        image:
            registry: quay.io
            repository: prometheus/pushgateway
            tag: v1.11.2
    server:
        image:
            registry: quay.io
            repository: prometheus/prometheus
            tag: v3.9.1
