images:
    - repository: quay.io/prometheus-operator/prometheus-config-reloader
      tag: v0.67.0
      path: configmapReload.prometheus.image
    - repository: quay.io/prometheus/prometheus
      tag: v2.48.0
      path: server.image
    - repository: quay.io/prometheus-operator/prometheus-config-reloader
      tag: v0.66.0
      path: alertmanager.configmapReload.image
    - repository: quay.io/prometheus/alertmanager
      tag: v0.26.0
      path: alertmanager.image
    - registry: registry.k8s.io
      repository: kube-state-metrics/kube-state-metrics
      tag: v2.10.1
      path: kube-state-metrics.image
    - registry: quay.io
      repository: brancz/kube-rbac-proxy
      tag: v0.14.0
      path: kube-state-metrics.kubeRBACProxy.image
    - registry: quay.io
      repository: prometheus/node-exporter
      tag: v1.7.0
      path: prometheus-node-exporter.image
    - registry: quay.io
      repository: brancz/kube-rbac-proxy
      tag: v0.15.0
      path: prometheus-node-exporter.kubeRBACProxy.image
    - repository: quay.io/prometheus/pushgateway
      tag: v1.6.2
      path: prometheus-pushgateway.image
