prometheus:
    alertmanager:
        image:
            repository: ""
    configmapReload:
        prometheus:
            image:
                repository: ""
    kube-state-metrics:
        image:
            repository: ""
        kubeRBACProxy:
            image:
                repository: ""
    prometheus-node-exporter:
        image:
            repository: ""
    prometheus-pushgateway:
        image:
            repository: ""
    server:
        image:
            repository: ""
