prometheus:
    alertmanager:
        image:
            registry: ghcr.io/descope
            repository: prometheus/alertmanager
            tag: v0.31.0-patched
    configmapReload:
        prometheus:
            image:
                registry: ghcr.io/descope
                repository: prometheus-operator/prometheus-config-reloader
                tag: v0.89.0-patched
    kube-state-metrics:
        image:
            registry: ghcr.io/descope
            repository: kube-state-metrics/kube-state-metrics
            tag: v2.18.0-patched
        kubeRBACProxy:
            image:
                registry: ghcr.io/descope
                repository: brancz/kube-rbac-proxy
                tag: v0.20.2-patched
    prometheus-node-exporter:
        image:
            registry: ghcr.io/descope
            repository: prometheus/node-exporter
            tag: v1.10.2-patched
    prometheus-pushgateway:
        image:
            registry: ghcr.io/descope
            repository: prometheus/pushgateway
            tag: v1.11.2-patched
    server:
        image:
            registry: ghcr.io/descope
            repository: prometheus/prometheus
            tag: v3.9.1-patched
