apiVersion: v2
name: prometheus-verity
description: prometheus with Copa-patched container images
type: application
version: 25.8.0-0
dependencies:
    - name: prometheus
      version: 28.9.0
      repository: oci://ghcr.io/prometheus-community/charts
