prometheus:
    kube-state-metrics:
        image:
            registry: ghcr.io/descope
            repository: kube-state-metrics/kube-state-metrics
            tag: v2.10.1-patched
        kubeRBACProxy:
            image:
                registry: ghcr.io/descope
                repository: brancz/kube-rbac-proxy
                tag: v0.14.0-patched
    prometheus-node-exporter:
        kubeRBACProxy:
            image:
                registry: ghcr.io/descope
                repository: brancz/kube-rbac-proxy
                tag: v0.15.0-patched
